
project_id = "uttebgyhijrdcjiczxrg"

[functions.twilio-webhook-proxy]
verify_jwt = false

[functions.twilio-call-webhook]
verify_jwt = false

[functions.twilio-media-stream] 
verify_jwt = false
timeout_seconds = 1800
max_duration = 1800

