
project_id = "exp-realty-conversations-ai"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.github]
enabled = true
client_id = "env(SUPABASE_AUTH_GITHUB_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GITHUB_SECRET)"
redirect_uri = "http://localhost:54323/auth/v1/callback"

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[experimental]
preserves_insertion_order = true

[functions]
  [functions.elevenlabs-signed-url]
  verify_jwt = true
  
  [functions.elevenlabs-voices]
  verify_jwt = true
  
  [functions.generate-speech]
  verify_jwt = true
  
  [functions.generate-with-ai]
  verify_jwt = true
  
  [functions.twilio-call-status]
  verify_jwt = true
  
  [functions.twilio-call-webhook]
  verify_jwt = false
  
  [functions.twilio-make-call]
  verify_jwt = true
  
  [functions.twilio-process-response]
  verify_jwt = true
  
  [functions.verify-twilio-creds]
  verify_jwt = true
  
  [functions.twilio-media-stream]
  verify_jwt = false
