
project_id = "uttebgyhijrdcjiczxrg"

[functions.twilio-call-webhook]
verify_jwt = false

[functions.twilio-process-response]
verify_jwt = false

[functions.generate-with-ai]
verify_jwt = false

[functions.generate-speech]
verify_jwt = false

[functions.twilio-make-call]
verify_jwt = false

